[workspace]

members = [
    "seq_tools",
    "seq_lib",
    "scan_ui",
    "scan_control",
    "build_sequence"
]

# this determines which package is the entry point for cargo run
default-members = ["scan_ui"]