[package]
name = "seq_tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
encoding = "0.2"
itertools = "0.10.3"
serde_json = "1.0"
serde = { version = "1.0.144", features = ["derive"] }
