[package]
name = "utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
walkdir = "2"
rustfft = "6.1.0"
num-complex = "0.4.2"
chrono = "0.4.23"
clean-path = "0.2.1"
lettre = "0.10.1"