[package]
name = "seq_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.19.0"
seq_lib = {path = "../seq_lib"}
seq_tools = {path = "../seq_tools"}